/* Copyright 2021 Carlos Gil, Daniel Moreno.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#pragma once

#include "Arduino.h"
#include "constants.h"

/// @file output_handler.h
///
/// @brief Handler to make sense of the output generated by the Interpreter and
/// do something with it.
///
/// @details The result inferred by the Interpreter which is contained within
/// the output tensor presents the probabilistic distribution generated by the
/// softmax function. The output handler receives this distribution through
/// recognizeLabel(int8_t*, uint8_t, bool) and extracts the place where the
/// maximum value of the resultant vector is located.
///
/// It also calculates the certainty of the prediction by mapping the 8-bit
/// range (-128, 127) to a scale 0-100 to display it when the formal parameter
/// `msgVerbose` is set to `true`.

uint8_t recognizeLabel(int8_t* arr, bool msgVerbose);
